### PR TITLE
Add fxthomas's signing key to the keyring

### PR DESCRIPTION
**Pull request by fxthomas**

### CODE REVIEW

**Comment by muff1nman** [comment]
Can you ensure your key is published on a keyserver? I couldn't find it.

**Comment by fxthomas** [comment]
I use gpg's defaut keyserver, `gpg --recv-key <id>` should work.

**Comment by muff1nman** [comment]
Ah found it with recv keys, I was assuming I should be able to see it via search on one of the keyservers. Doesn't work that way apparently. Anyways should be good to go now.

**Comment by muff1nman** [comment]
Ah found it with recv keys, I was assuming I should be able to see it via search on one of the keyservers. Doesn't work that way apparently. Anyways should be good to go now.

**Comment by fxthomas** [comment]
Ah, nice! Tbf I haven't used gpg a lot, so I could have used it the wrong way!

**Comment by jvoisin** [comment]
Welcome to the gang @fxthomas !

**Pull request merged**
